name: Publish to pub.dev on Tag

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Publish
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          environment: pub.dev
