name: Publish to pub.dev on Tag

on:
  workflow_dispatch:
  # release:
  #   types:
  #     - published

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: ${{ github.event.release.tag_name }}

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Publish to pub.dev
        run: dart pub publish --force
